# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libfreetype6-dev
    - libjpeg-dev
    - python3-dev
    - python3-numpy

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Install dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
